name: BestCasino-EN
main: Coline\Casino\BestCasinoMain
author: Alexey, translated by Zeao
version: 2.0.0
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10]
load: STARTUP
website: Not showing.
commands:
    settingcasino:
        description: "Casino Settings"


 
